# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0002_logacn_logtxn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacn',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
