# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0003_auto_20180415_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
