# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='user',
            name='date_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logtxn',
            name='content',
            field=models.TextField(),
        ),
    ]
