# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='Date Published')),
                ('start_date', models.DateTimeField(verbose_name='Date start')),
                ('end_date', models.DateTimeField(verbose_name='Date end')),
                ('meeting_user', models.CharField(max_length=200)),
                ('meeting_content', models.CharField(max_length=300)),
            ],
        ),
    ]
