# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('title_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
