# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
    ]
